### ISSUE TITLE
Rotary switch type

### ISSUE THREAD

**Issue by g4oep** [brianlow/Rotary#13]
I want to make a controller for a si5351 signal generator, and have found a sketch which uses Rotary.h.  I notice that Rotary.h is designed for a switch which makes 4 changes per click.  I have bought a typical switch from ebay, but find that it makes just one change of state per click, going 00, 01, 11, 00 over 4 clicks.  Is there any way in which rotary.h can be used or modified to suit this type of switch ?  An alternative approach would be to find the intended type of switch which makes all 4 changes in 1 click.  But where does one look for this type of switch ?  I suspect that all of the easily available switches on ebay advertised as being suitable for arduino projects are of the simpler type making one change per click.  Comments much appreciated

**Comment by voneiden** [comment]
Link to said product? I've got a few different cheap ebay rotary encoder variants and all of them emit more than one code per detent. 

Also just in case, curious what was your method of determining the output change per click?

**Comment by voneiden** [comment]
I just tested two no-name brands, the most commonly sold deep blue ones and the almost equally common turquoise ones and they both emit a similar gray code.
![2021-03-02-233327_2560x1440_scrot](https://user-images.githubusercontent.com/437576/109727922-e5d66300-7bbd-11eb-843b-9951f2055791.jpg)

**Comment by voneiden** [comment]
Pictures of said encoders. I guess they're both Alpine EC11 knock-offs.

![IMG_20210303_011624__01](https://user-images.githubusercontent.com/437576/109728151-554c5280-7bbe-11eb-8d91-6e412cc82f5c.jpg)

**Comment by g4oep** [comment]
Thanks guys - this is very strange.  The switch I am using is identical to the ones shown here, but it is definitely different electrically.  Each switch changes state once per click, but with a time delay so that one change precedes the other (see cro pic).  The pic I have posted shows 2 clicks.  The characteristic can be confirmed with a voltmeter, since each channel changes to a stable state after each click which is the inverse of what it was before.  Put another way, both channels always have the same steady state (00 or 11) before a click, and change to the opposite steady state after a click - 00, 11, 00, 11 etc, this being 3 clicks.  I bought the switch on ebay.  These items on ebay abound, and all look alike, but none clearly specify their characteristics, so it seems that there is no way of being clear about what you are buying

https://www.ebay.co.uk/itm/Rotary-Shaft-Encoder-EC11-style-with-push-switch-UK-stock/193829372465?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2057872.m2749.l2649


![pic_67_3](https://user-images.githubusercontent.com/79785493/109851952-28df1780-7c4c-11eb-8331-3526e72b853d.jpg)

**Comment by voneiden** [comment]
Oh I get it.  I've not encountered those kinds yet, but as far as I understand this library does support also encoders which should emit  at 00 and 11. From the readme:

> It's also possible to use 'half-step' mode. This just emits an event at both the 0-0 and 1-1 positions. This might be useful for some encoders where you want to detect all positions. In rotary.h, uncomment #define HALF_STEP to enable half-step mode.

The readme refers to this line https://github.com/brianlow/Rotary/blob/master/Rotary.h#L11

Would that work in your case?

**Comment by g4oep** [comment]
thanks - I'll try that

**Comment by voneiden** [comment]
@g4oep presumably this got resolved?

**Comment by brianlow** [comment]
Thanks @voneiden!

Closing for now, feel fee to re-open to continue to discussion
