### ISSUE TITLE
where to put?

### ISSUE THREAD

**Issue by tarbear123** [brianlow/Rotary#6]
do i just put the "Rotary.h" file into the atom folder and do i do the same thing with other libraries i download?

**Comment by voneiden** [comment]
You can place both the h and cpp in the same folder as your main code and include them as local files. If you want to install them as system wide libraries then refer to your toolchain documentation.

**Comment by tarbear123** [comment]
ok but where do i put the "Rotary.h" file into, the atom folder or the platformio folder? and do i do the same thing with other libraries i download?

**Comment by voneiden** [comment]
Please refer to your toolchain documentation: 

http://docs.platformio.org/en/latest/userguide/lib/cmd_install.html
